### ISSUE TITLE
Unable to create new bookmarks. 

### ISSUE THREAD

**Issue by testbughub** [bachya/linkding-cli#153]
**Describe the bug**
I'm attempting to create a new bookmark, but I always get the same error - "async_create() got an unexpected keyword argument 'archived'"

**To Reproduce**

```
$ linkding bookmarks create -t "Example" --tags Tag1 "http://example.com"  
2023-07-11 18:59:47,396 | linkding_cli | ERROR | async_create() got an unexpected keyword argument 'archived'
```

**Expected behavior**
Successfully creating a new bookmark. 

**Additional context**
Not really sure if I'm doing something wrong,  
but if any more info is needed, just let me know.

**Comment by bachya** [comment]
I'm unable to reproduce this. Using version 2022.11.0, this command:

```
$ linkding -t REDACTED -u REDACTED create -t "Example" --tags Tag1 "http://example.com"
```

...gave me the expected result:

```
{"id": 1101, "url": "http://example.com", "title": "Example", "description": "", "notes": "", "website_title": "Example Domain", "website_description": null, "is_archived": false, "unread": false, "shared": false, "tag_names": ["tag1"], "date_added": "2023-07-11T20:34:54.972570Z", "date_modified": "2023-07-11T20:34:54.972574Z"}
```
![CleanShot 2023-07-11 at 14 35 54](https://github.com/bachya/linkding-cli/assets/47216/4ebb52e7-3f9d-40eb-88e4-7743f5267834)

To help debug, please provide the following:

1. What version are you using?
2. How did you install `linkding-cli`?

**Comment by testbughub** [comment]
Trough pip.  
I noticed now that it isn't the most recent version (I have 2022.8.0).  
How do I install it with the source files?

**Comment by bachya** [comment]
Try this:

```
pip install --upgrade linkding-cli
```

**Comment by testbughub** [comment]
That's how I installed it.  
[output](https://pastebin.com/mBNMD5kT)

**Comment by bachya** [comment]
```
Requirement already satisfied: linkding-cli in /home/user/.local/lib/python3.8/site-packages (2022.8.0)
```

You're using Python 3.8—the last `linkding-cli` version that supported 3.8 was 2022.8.0. Per [the docs](https://github.com/bachya/linkding-cli#python-versions), if you want to upgrade to the latest, you must upgrade to Python 3.9.

**Comment by testbughub** [comment]
Oops, I missed that part in the README. My bad.  
I updated python and reinstalled linkding-cli, and it works now.  
Thanks!
